version: '3'

services:
  api:
    build: ./api
    command: gunicorn maruapi.wsgi:application --bind 0.0.0.0:8000
    entrypoint: /app/bin/entrypoint.sh
    env_file:
      - .env
    volumes:
      - ./api:/app
      - ./media:/media
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
  nginx:
    image: nginx:latest
    ports:
      - "9001:9001"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./media:/media

