version: '3'

services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - PUBLIC_URL=/public
    volumes:
      - /app/node_modules
      - ./web:/app
  api:
    build: ./api
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    entrypoint: /app/bin/entrypoint.sh
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch
    volumes:
      - ./api:/app
      - ./media:/media
      - ./api/static:/static
  celery:
    build: ./api
    command: celery -A core worker
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./api:/app
      - ./media:/media
  db:
    image: postgres
    env_file:
      - .env
  redis:
    image: redis:alpine
  elasticsearch:
    image: elasticsearch:7.9.2
    env_file:
      - ./config/elasticsearch.env
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - api
      - web
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./media:/media
      - ./api/static:/static
      - ./web/public:/public

