version: '3'

services:
  web:
    build: ./web
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./web:/app
  api:
    build: ./api
    env_file:
      - .env # edit MARU_DATABASE for postres
    ports:
      - "8000:8000"
    # depends_on: # uncomment for postgres
    #   - db
    volumes:
      - ./api:/app
      - ./media:/media
      - ./artwork:/artwork
      - ./api/static:/static
  # db:
  #   image: postgres
  #   env_file:
  #     - .env
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - api
      - web
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./media:/media
      - ./api/static:/static
      - ./web/public:/public

