version: '3'

services:
  web:
    image: jordanribera/maru-web
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./web:/app
  api:
    image: jordanribera/maru-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./media:/media
      - ./api/static:/static
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - api
      - web
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./media:/media
      - ./api/static:/static
      - ./web/public:/public

