steps:
  - label: ":docker: prebuild images"
    plugins:
      - docker-login#v2.0.1:
          username: jordanribera
      - docker-compose#v3.7.0:
          build: api
          config: docker-compose.yml
          image-repository: index.docker.io/jordanribera/maru-api
          push: api:maru-api:latest
      - docker-compose#v3.7.0:
          build: web
          config: docker-compose.yml
          image-repository: index.docker.io/jordanribera/maru-web
          push: api:maru-web:latest
  - wait
  - label: ":eslint: eslint"
    # command: "npx eslint /app/src"
    command: "ls /app"
    plugins:
      - docker-login#v2.0.1:
          username: jordanribera
      - docker#v3.7.0:
          image: "jordanribera/maru-web"
  - label: ":nail_care: prettier"
    command: "npx prettier -c /app/src"
    plugins:
      - docker-login#v2.0.1:
          username: jordanribera
      - docker#v3.7.0:
          image: "jordanribera/maru-web"
  - label: ":nail_care: flake8"
    command: "flake8 /app/src"
    plugins:
      - docker-login#v2.0.1:
          username: jordanribera
      - docker#v3.7.0:
          image: "jordanribera/maru-api"
