steps:
  - label: ":wrench: new prebuild"
    command: ".buildkite/steps/dockerbuild.sh"
    plugins:
      - docker-login#v2.0.1:
          username: jordanribera

  - wait

  - label: ":eslint: eslint"
    command: "npx eslint /app/src"
    plugins:
      - docker-login#v2.0.1:
          username: jordanribera
      - docker#v3.7.0:
          image: "jordanribera/maru-web:${BUILDKITE_COMMIT:0:7}"
  - label: ":nail_care: prettier"
    command: "npx prettier -c /app/src"
    plugins:
      - docker-login#v2.0.1:
          username: jordanribera
      - docker#v3.7.0:
          image: "jordanribera/maru-web:${BUILDKITE_COMMIT:0:7}"
  - label: ":nail_care: flake8"
    command: "flake8 /app/src"
    plugins:
      - docker-login#v2.0.1:
          username: jordanribera
      - docker#v3.7.0:
          image: "jordanribera/maru-api:${BUILDKITE_COMMIT:0:7}"

  - wait

  - label: ":docker: push *:latest"
    command: ".buildkite/steps/dockerpush.sh"
    plugins:
      - docker-login#v2.0.1:
          username: jordanribera
